services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: won_admin
      POSTGRES_PASSWORD: wonadmin
      POSTGRES_DB: won-
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -u ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
